version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=pradip
      - DB_PASSWORD=password
      - DB_DATABASE=test
    networks:
      - app-network
      # wait for the database container to be ready
    depends_on:
      - db

  setup: # setup container
    build: 
      context: .
      dockerfile: Dockerfile.setup
    environment:
      - DB_HOST=db
      - DB_USER=pradip
      - DB_PASSWORD=password
      - DB_DATABASE=test
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: pradip
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
